version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_DATABASE="shopDb"
      - Mongo_ROOT_USERNAME="root"
      - Mongo_ROOT_PASSWORD="root"
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - 8081:8081
        
